language: cpp
compiler: g++

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install g++-7 binutils-2.26
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - export PATH=/usr/lib/binutils-2.26/bin:${PATH}

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - cmake
    - time
    - g++-7
    - gcc-7
    - binutils
    - libc6
    - libc6-amd64
    - libc6-dev
    - libc6-dbg
    - python

script:
  - make test

cache:
    apt: true
    directories:
    - vendor

# Only build on the master branch
# Others are handled by Pull Requests
branches:
  only:
  - master

notifications:
  on_success: false
  email: false
